services:
  app:
    environment:
      AWS_REGION: eu-west-1
      DAFT_DYNAMO_ENDPOINT: ""
      SSM_PARAM_PREFIX: /daftiescanner/prod
      MANAGEMENT_METRICS_EXPORT_CLOUDWATCH_ENABLED: "true"
    logging:
      driver: awslogs
      options:
        awslogs-group: /daftiescanner/app
        awslogs-region: eu-west-1
        awslogs-stream-prefix: app
        awslogs-create-group: "true"
